version: '3'

services:

  app:
    build: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    command: "npm start"
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

